### ISSUE TITLE
Global binaries not available by default

### ISSUE THREAD

**Issue by hadim** [prefix-dev/pixi-docker#63] opened 2024-12-12 20:41 UTC
```bash
$ docker run --rm -ti ghcr.io/prefix-dev/pixi bash -c "pixi global install rsync && rsync --version"
Global environments as specified in '/root/.pixi/manifests/pixi-global.toml'
└── rsync: 3.3.0 (installed)
    └─ exposes: rsync, rsync-ssl
bash: line 1: rsync: command not found
```

This is because `/root/.pixi/bin/` is not in the `PATH` by default.

What are your thoughts on making the global binaries available by default in the docker image? 

A legit use case is to quickly install tools and use them in the docker image. For example, the above command is actually much faster than using the `ubuntu` docker image with `apt update && apt install rsync`.

**Comment by hadim** [comment] 2024-12-12 20:45
Eventually we could set `export PIXI_HOME=/usr/local` but this might have unwanted side effects.

**Comment by pavelzw** [comment] 2024-12-13 09:44
I think this makes sense. I don't think there is a way to append to env variables (i.e. `export PATH="/root/.pixi/bin:$PATH"`) in Docker syntax, the only way is to overwrite it using `ENV PATH=...`.
Before doing this, we should make sure we don't accidentally delete parts of the `PATH` of the base images (or add too much).

https://github.com/prefix-dev/pixi-docker/blob/1c419658eae9ce5fc61fceed97538ae43a2d7777/.github/workflows/build.yml#L42-L63

PRs are welcome

**Comment by pavelzw** [comment] 2024-12-13 09:45
just saw this is a duplicate of #40

**Closed as duplicate by pavelzw** 2024-12-13 09:45 UTC
Labels: enhancement
